#!/usr/bin/env python3
"""
Unified Local Runtime Server for Observatorio LATAM.
Zero external runtime dependencies — uses Python standard library only.
Serves:
- GET / -> web/portal/index.html
- GET /web/portal/* -> static files with appropriate MIME types
- GET /data/public/* -> snapshot JSON files with application/json MIME type
- POST /api/chat -> verified agentic chat responses via etl.chat_engine.answer_question
- OPTIONS * -> CORS preflight headers with HTTP 200
"""

from __future__ import annotations
import argparse
import http.server
import json
import mimetypes
import os
from pathlib import Path
import socket
import sys
import threading
import time
import urllib.parse
import urllib.request
from typing import Optional, Tuple

ROOT_DIR = Path(__file__).resolve().parent
WEB_PORTAL_DIR = ROOT_DIR / "web" / "portal"
DATA_PUBLIC_DIR = ROOT_DIR / "data" / "public"

# Ensure etl module can be imported
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

try:
    from etl.chat_engine import SnapshotStore, answer_question
except ImportError:
    sys.path.append(str(Path(__file__).resolve().parent))
    from etl.chat_engine import SnapshotStore, answer_question

# Initialize mime types
mimetypes.init()
mimetypes.add_type("application/json", ".json")
mimetypes.add_type("text/javascript", ".js")
mimetypes.add_type("application/javascript", ".js")
mimetypes.add_type("text/css", ".css")
mimetypes.add_type("image/svg+xml", ".svg")
mimetypes.add_type("text/html", ".html")
mimetypes.add_type("text/plain", ".txt")
mimetypes.add_type("text/csv", ".csv")

# Global SnapshotStore instance for fast in-memory reuse
GLOBAL_STORE: Optional[SnapshotStore] = None
STORE_LOCK = threading.Lock()


def get_store() -> SnapshotStore:
    global GLOBAL_STORE
    if GLOBAL_STORE is None:
        with STORE_LOCK:
            if GLOBAL_STORE is None:
                GLOBAL_STORE = SnapshotStore()
    return GLOBAL_STORE


def is_safe_subpath(path: Path, base: Path) -> bool:
    try:
        path.resolve().relative_to(base.resolve())
        return True
    except ValueError:
        return False


class ObservatorioHandler(http.server.BaseHTTPRequestHandler):
    server_version = "ObservatorioServer/1.0"

    def send_cors_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, HEAD")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Requested-With")
        self.send_header("Access-Control-Max-Age", "86400")

    def do_OPTIONS(self) -> None:
        self.send_response(200)
        self.send_cors_headers()
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_HEAD(self) -> None:
        self.handle_get_or_head(is_head=True)

    def do_GET(self) -> None:
        self.handle_get_or_head(is_head=False)

    def handle_get_or_head(self, is_head: bool = False) -> None:
        parsed_url = urllib.parse.urlparse(self.path)
        clean_path = urllib.parse.unquote(parsed_url.path)

        # 1. Root and index endpoint: GET /
        if clean_path in ("/", "", "/index.html"):
            index_path = WEB_PORTAL_DIR / "index.html"
            if index_path.is_file():
                self.serve_file(index_path, is_head=is_head, mime_type="text/html; charset=utf-8")
            else:
                # Fallback HTML if web/portal/index.html is still being generated by parallel worker
                fallback_html = (
                    b"<!DOCTYPE html>\n<html lang=\"es\">\n<head>\n"
                    b"  <meta charset=\"UTF-8\">\n"
                    b"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                    b"  <title>Observatorio LATAM</title>\n</head>\n<body>\n"
                    b"  <h1>Observatorio LATAM</h1>\n"
                    b"  <p>Servidor local unificado activo. Portal web en inicializaci\xc3\xb3n.</p>\n"
                    b"</body>\n</html>\n"
                )
                self.send_response(200)
                self.send_cors_headers()
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(fallback_html)))
                self.end_headers()
                if not is_head:
                    self.wfile.write(fallback_html)
            return

        # 2. Public snapshot files: /data/public/*
        if clean_path.startswith("/data/public/"):
            rel_path = clean_path[len("/data/public/"):].lstrip("/")
            target_file = (DATA_PUBLIC_DIR / rel_path).resolve()
            if not is_safe_subpath(target_file, DATA_PUBLIC_DIR):
                self.send_error_response(403, "Forbidden path", is_head)
                return
            if not target_file.is_file():
                self.send_error_response(404, f"File not found: {clean_path}", is_head)
                return
            self.serve_file(target_file, is_head=is_head, mime_type="application/json; charset=utf-8")
            return

        # 3. Static portal files: /web/portal/* or /portal/*
        if clean_path.startswith("/web/portal/"):
            rel_path = clean_path[len("/web/portal/"):].lstrip("/")
            target_file = (WEB_PORTAL_DIR / rel_path).resolve()
            if not is_safe_subpath(target_file, WEB_PORTAL_DIR):
                self.send_error_response(403, "Forbidden path", is_head)
                return
            if not target_file.is_file():
                self.send_error_response(404, f"File not found: {clean_path}", is_head)
                return
            self.serve_file(target_file, is_head=is_head)
            return

        if clean_path.startswith("/portal/"):
            rel_path = clean_path[len("/portal/"):].lstrip("/")
            target_file = (WEB_PORTAL_DIR / rel_path).resolve()
            if not is_safe_subpath(target_file, WEB_PORTAL_DIR):
                self.send_error_response(403, "Forbidden path", is_head)
                return
            if not target_file.is_file():
                self.send_error_response(404, f"File not found: {clean_path}", is_head)
                return
            self.serve_file(target_file, is_head=is_head)
            return

        # 4. Direct assets at root level mapped to portal (e.g. /portal.css, /portal.js, /favicon.ico)
        direct_portal_file = (WEB_PORTAL_DIR / clean_path.lstrip("/")).resolve()
        if (
            direct_portal_file.is_file()
            and is_safe_subpath(direct_portal_file, WEB_PORTAL_DIR)
            and not clean_path.startswith("/api/")
            and not clean_path.startswith("/data/")
        ):
            self.serve_file(direct_portal_file, is_head=is_head)
            return

        # 5. Method not allowed for GET /api/chat
        if clean_path == "/api/chat":
            self.send_response(405)
            self.send_cors_headers()
            self.send_header("Allow", "POST, OPTIONS")
            self.send_header("Content-Type", "application/json; charset=utf-8")
            msg = json.dumps({"error": "Method Not Allowed. Use POST /api/chat."}).encode("utf-8")
            self.send_header("Content-Length", str(len(msg)))
            self.end_headers()
            if not is_head:
                self.wfile.write(msg)
            return

        # 6. Fallback: 404
        self.send_error_response(404, f"Not Found: {clean_path}", is_head)

    def do_POST(self) -> None:
        parsed_url = urllib.parse.urlparse(self.path)
        clean_path = urllib.parse.unquote(parsed_url.path)

        if clean_path == "/api/chat":
            self.handle_api_chat()
            return

        self.send_error_response(404, f"Endpoint not found: {clean_path}")

    def handle_api_chat(self) -> None:
        content_length_header = self.headers.get("Content-Length")
        if not content_length_header:
            self.send_json_response(400, {"error": "Content-Length header is required"})
            return

        try:
            content_length = int(content_length_header)
            raw_body = self.rfile.read(content_length)
        except Exception as e:
            self.send_json_response(400, {"error": f"Failed to read request body: {str(e)}"})
            return

        try:
            payload = json.loads(raw_body.decode("utf-8"))
        except Exception as e:
            self.send_json_response(400, {"error": f"Invalid JSON body: {str(e)}"})
            return

        question = str(payload.get("question") or "").strip()
        if not question:
            self.send_json_response(400, {"error": "Field 'question' is required and cannot be empty"})
            return

        try:
            store = get_store()
            response_data = answer_question(question, store=store)
            self.send_json_response(200, response_data)
        except Exception as e:
            self.send_json_response(500, {"error": f"Internal server error processing question: {str(e)}"})

    def serve_file(self, file_path: Path, is_head: bool = False, mime_type: Optional[str] = None) -> None:
        try:
            data = file_path.read_bytes()
        except OSError as e:
            self.send_error_response(500, f"Error reading file: {str(e)}", is_head)
            return

        if not mime_type:
            guessed_type, _ = mimetypes.guess_type(str(file_path))
            mime_type = guessed_type or "application/octet-stream"
            if mime_type.startswith("text/") or mime_type in ("application/javascript", "application/json"):
                mime_type += "; charset=utf-8"

        self.send_response(200)
        self.send_cors_headers()
        self.send_header("Content-Type", mime_type)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()

        if not is_head:
            self.wfile.write(data)

    def send_json_response(self, status_code: int, data: dict) -> None:
        json_bytes = json.dumps(data, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(status_code)
        self.send_cors_headers()
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(json_bytes)))
        self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
        self.end_headers()
        self.wfile.write(json_bytes)

    def send_error_response(self, status_code: int, message: str, is_head: bool = False) -> None:
        error_dict = {"status": status_code, "error": message}
        error_bytes = json.dumps(error_dict, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(status_code)
        self.send_cors_headers()
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(error_bytes)))
        self.end_headers()
        if not is_head:
            self.wfile.write(error_bytes)

    def log_message(self, format: str, *args) -> None:
        sys.stderr.write(f"[{self.log_date_time_string()}] {self.address_string()} - {format % args}\n")


def parse_arguments() -> Tuple[str, int, bool]:
    parser = argparse.ArgumentParser(
        description="Observatorio LATAM — Unified Local Runtime Server",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("port_pos", nargs="?", type=int, default=None, help="Port to listen on (positional)")
    parser.add_argument("-p", "--port", type=int, default=None, help="Port to listen on (-p/--port)")
    parser.add_argument("--host", default="0.0.0.0", help="Network interface to bind to")
    parser.add_argument("--test", action="store_true", help="Run automated endpoint verification in test mode")

    args = parser.parse_args()

    port = 8000
    if args.port is not None:
        port = args.port
    elif args.port_pos is not None:
        port = args.port_pos
    elif "PORT" in os.environ:
        try:
            port = int(os.environ["PORT"])
        except ValueError:
            port = 8000

    return args.host, port, args.test


def create_server(host: str = "0.0.0.0", port: int = 8000) -> http.server.ThreadingHTTPServer:
    get_store()
    server_address = (host, port)
    server = http.server.ThreadingHTTPServer(server_address, ObservatorioHandler)
    return server


def run_server(host: str = "0.0.0.0", port: int = 8000) -> None:
    server = create_server(host, port)
    print(f"[Observatorio LATAM] Unified local server running on http://{host}:{port}/")
    print(f"[Observatorio LATAM] Root portal: http://{host}:{port}/")
    print(f"[Observatorio LATAM] Snapshot data: http://{host}:{port}/data/public/manifest.json")
    print(f"[Observatorio LATAM] Agentic Chat API: POST http://{host}:{port}/api/chat")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[Observatorio LATAM] Shutting down gracefully...")
        server.shutdown()
        server.server_close()


def run_test_mode(host: str = "127.0.0.1", port: int = 8999) -> int:
    """Automated integration test mode for server verification."""
    print(f"[TEST MODE] Starting server on {host}:{port} for verification...")
    server = create_server(host, port)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    time.sleep(0.3)

    base_url = f"http://{host}:{port}"
    tests_passed = 0
    total_tests = 6

    try:
        # Test 1: GET /
        print(f"  [1/{total_tests}] Testing GET / ...", end=" ")
        req = urllib.request.Request(f"{base_url}/")
        with urllib.request.urlopen(req) as resp:
            assert resp.getcode() == 200, f"Expected 200, got {resp.getcode()}"
            assert "text/html" in resp.headers.get("Content-Type", "")
            body = resp.read()
            assert len(body) > 0
            print("OK (HTTP 200, text/html)")
            tests_passed += 1

        # Test 2: GET /data/public/manifest.json
        print(f"  [2/{total_tests}] Testing GET /data/public/manifest.json ...", end=" ")
        req = urllib.request.Request(f"{base_url}/data/public/manifest.json")
        with urllib.request.urlopen(req) as resp:
            assert resp.getcode() == 200, f"Expected 200, got {resp.getcode()}"
            assert "application/json" in resp.headers.get("Content-Type", "")
            data = json.loads(resp.read().decode("utf-8"))
            assert "zenodo_doi" in data, "manifest missing zenodo_doi"
            print(f"OK (HTTP 200, DOI: {data.get('zenodo_doi')})")
            tests_passed += 1

        # Test 3: GET /data/public/insights.json
        print(f"  [3/{total_tests}] Testing GET /data/public/insights.json ...", end=" ")
        req = urllib.request.Request(f"{base_url}/data/public/insights.json")
        with urllib.request.urlopen(req) as resp:
            assert resp.getcode() == 200, f"Expected 200, got {resp.getcode()}"
            assert "application/json" in resp.headers.get("Content-Type", "")
            data = json.loads(resp.read().decode("utf-8"))
            assert "latest_regional_stats" in data
            print("OK (HTTP 200, valid JSON)")
            tests_passed += 1

        # Test 4: OPTIONS /api/chat (CORS preflight)
        print(f"  [4/{total_tests}] Testing OPTIONS /api/chat ...", end=" ")
        req = urllib.request.Request(f"{base_url}/api/chat", method="OPTIONS")
        with urllib.request.urlopen(req) as resp:
            assert resp.getcode() == 200, f"Expected 200, got {resp.getcode()}"
            assert resp.headers.get("Access-Control-Allow-Origin") == "*"
            print("OK (HTTP 200, CORS Allow-Origin: *)")
            tests_passed += 1

        # Test 5: POST /api/chat (In-catalog)
        print(f"  [5/{total_tests}] Testing POST /api/chat (in-catalog) ...", end=" ")
        payload = json.dumps({
            "question": "¿Cuánto emite de CO2 per cápita Colombia y cómo se compara con el promedio regional?"
        }).encode("utf-8")
        req = urllib.request.Request(
            f"{base_url}/api/chat",
            data=payload,
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req) as resp:
            assert resp.getcode() == 200, f"Expected 200, got {resp.getcode()}"
            data = json.loads(resp.read().decode("utf-8"))
            assert data.get("out_of_catalog") is False
            assert data.get("verification", {}).get("passed") is True
            assert data.get("verification", {}).get("unverified_count") == 0
            assert data.get("chart") is not None
            assert "comparator_url" in data["chart"]
            assert len(data.get("sources", [])) > 0
            print(f"OK (HTTP 200, 100% verified, unverified=0, indicator={data['chart']['indicator']})")
            tests_passed += 1

        # Test 6: POST /api/chat (Out-of-catalog)
        print(f"  [6/{total_tests}] Testing POST /api/chat (out-of-catalog) ...", end=" ")
        payload = json.dumps({
            "question": "¿Cuál fue el precio de Bitcoin en Colombia en 2024?"
        }).encode("utf-8")
        req = urllib.request.Request(
            f"{base_url}/api/chat",
            data=payload,
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req) as resp:
            assert resp.getcode() == 200, f"Expected 200, got {resp.getcode()}"
            data = json.loads(resp.read().decode("utf-8"))
            assert data.get("out_of_catalog") is True
            assert "Dato fuera del catálogo" in data.get("badge", "")
            assert data.get("verification", {}).get("unverified_count") == 0
            assert data.get("chart") is None
            print(f"OK (HTTP 200, out_of_catalog=True, 0 hallucinations)")
            tests_passed += 1

        print(f"\n[TEST SUMMARY] All {tests_passed}/{total_tests} server tests passed successfully.")
        return 0

    except Exception as e:
        print(f"\n[TEST FAILED] {e}")
        return 1

    finally:
        server.shutdown()
        server.server_close()


if __name__ == "__main__":
    bind_host, bind_port, is_test = parse_arguments()
    if is_test:
        sys.exit(run_test_mode(bind_host, bind_port if bind_port != 8000 else 8999))
    else:
        run_server(bind_host, bind_port)
